// Package similapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package similapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for NodeType.
const (
	Document NodeType = "document"
	Folder   NodeType = "folder"
)

// CreateRecordsRequest The object is used for records creation.
type CreateRecordsRequest struct {
	// Document The binary data for the document of the specified format.
	Document []byte `json:"document"`

	// NodeType The object describes the index node type.
	NodeType NodeType `json:"nodeType"`

	// Parser The parser name (format name) to be used for the document body.
	Parser string `json:"parser"`

	// RankMultiplier The priority coefficient (must be >= 1.0) of the records within a search result set, the value is overridden by the rankMultiplier value specified for an individual record.
	RankMultiplier float32 `json:"rankMultiplier"`

	// Records The list of records that must be added to the node.
	Records []Record `json:"records"`

	// Tags The object describes the node tags.
	Tags Tags `json:"tags"`
}

// CreateRecordsResult The object is used as a response of the records creation request.
type CreateRecordsResult struct {
	// NodesCreated The list of nodes created.
	NodesCreated []Node `json:"nodesCreated"`

	// RecordsCreated The number of records created.
	RecordsCreated int `json:"recordsCreated"`
}

// DeleteNodesRequest The object is used to delete multiple nodes at a time
type DeleteNodesRequest struct {
	// FilterConditions The filter conditions. The filters support `and`, `or` and `not` conditions for `format`, `path` and `tag("name")`, for instance, `tag("public") = "true" and format = "spreadsheetsData" and (path = "/orgs/1234/balance.xlsx" or path like "/org%"))`.
	FilterConditions string `json:"filterConditions"`

	// Force The flag allows to delete children of a matched node, even if they don't meet the filter criteria
	Force bool `json:"force"`
}

// Format The object describes a data format.
type Format struct {
	// Basis The format basis specifies format dimensions.
	Basis []byte `json:"basis"`

	// Name The format name, it is used as the format identifier.
	Name string `json:"name"`
}

// Formats The object is used as a response of the formats list request.
type Formats struct {
	// Formats Contains a list of formats.
	Formats []Format `json:"formats"`
}

// ListNodesResult The object is used as a response of the nodes list request.
type ListNodesResult struct {
	// Items The list of nodes.
	Items []Node `json:"items"`
}

// ListRecordsResult The object is used a response to the list records request.
type ListRecordsResult struct {
	// NextPageId The id of the next page for getting the rest of the records.
	NextPageId *string `json:"nextPageId,omitempty"`

	// Records The list of found records.
	Records *[]Record `json:"records,omitempty"`

	// Total The total number of found records.
	Total int `json:"total"`
}

// Node The object describes the index node.
type Node struct {
	// Name The node name, must be unique among the siblings in the tree.
	Name string `json:"name"`

	// Path The node path, does not include the name part.
	Path string `json:"path"`

	// Tags The object describes the node tags.
	Tags Tags `json:"tags"`

	// Type The object describes the index node type.
	Type NodeType `json:"type"`
}

// NodeType The object describes the index node type.
type NodeType string

// PatchRecordsRequest The object is used to upsert and delete the node records.
type PatchRecordsRequest struct {
	// DeleteRecords The records to be deleted for the node.
	DeleteRecords []Record `json:"deleteRecords"`

	// UpsertRecords The records to be upserted for the node.
	UpsertRecords []Record `json:"upsertRecords"`
}

// PatchRecordsResult The object is used as a response to the patch records request.
type PatchRecordsResult struct {
	// Deleted The number of deleted records.
	Deleted int `json:"deleted"`

	// Upserted The number of upserted records.
	Upserted int `json:"upserted"`
}

// Record The object contains information about the index record.
type Record struct {
	// Format The format of the record.
	Format string `json:"format"`

	// Id The record identifier within the node.
	Id string `json:"id"`

	// RankMultiplier The priority coefficient (must be >= 1.0) of the record within a search result set.
	RankMultiplier float32 `json:"rankMultiplier"`

	// Segment The searchable text for the record.
	Segment string `json:"segment"`

	// Vector The vector data for the segment.
	Vector []byte `json:"vector"`
}

// SearchRecordsRequest The object is used to perform search across the index records.
type SearchRecordsRequest struct {
	// FilterConditions The filter conditions. The filters support `and`, `or` and `not` conditions for `format`, `path` and `tag("name")`, for instance, `tag("public") = "true" and format = "spreadsheetsData" and (path = "/orgs/1234/balance.xlsx" or prefix(path, "/org"))`.
	FilterConditions string `json:"filterConditions"`

	// GroupByPathOff The flag turns off results grouping by path.
	GroupByPathOff bool `json:"groupByPathOff"`

	// Limit The maximum number of records per page.
	Limit int `json:"limit"`

	// Offset The number of records to skip before start returning results.
	Offset int `json:"offset"`

	// TextQuery The text query. The query must be formed in accordance with the query language of the underlying search engine.
	TextQuery string `json:"textQuery"`
}

// SearchRecordsResult The object is used as a response to the search records request.
type SearchRecordsResult struct {
	// Items The found index records.
	Items []SearchRecordsResultItem `json:"items"`

	// Total The total number of found records.
	Total int `json:"total"`
}

// SearchRecordsResultItem The object is used as an item in the search records response.
type SearchRecordsResultItem struct {
	// MatchedKeywords The matched keywords within the record.
	MatchedKeywords []string `json:"matchedKeywords"`

	// Path The path of the record.
	Path string `json:"path"`

	// Record The object contains information about the index record.
	Record Record `json:"record"`

	// Score The relevancy score of the record.
	Score float32 `json:"score"`
}

// Tags The object describes the node tags.
type Tags map[string]string

// CreatedAfterFilter defines model for CreatedAfterFilter.
type CreatedAfterFilter = time.Time

// CreatedBeforeFilter defines model for CreatedBeforeFilter.
type CreatedBeforeFilter = time.Time

// Force defines model for Force.
type Force = bool

// FormatFilter defines model for FormatFilter.
type FormatFilter = string

// FormatId defines model for FormatId.
type FormatId = string

// Limit defines model for Limit.
type Limit = int

// PageId defines model for PageId.
type PageId = string

// Path defines model for Path.
type Path = string

// PathFilter defines model for PathFilter.
type PathFilter = string

// TagsFilter The object describes the node tags.
type TagsFilter = Tags

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	// Path The path specifies the path to filter by.
	Path *PathFilter `form:"path,omitempty" json:"path,omitempty"`
}

// DeleteNodeParams defines parameters for DeleteNode.
type DeleteNodeParams struct {
	// Force force flag specifies whether the operation will force the request.
	Force *Force `form:"force,omitempty" json:"force,omitempty"`
}

// ListNodeRecordsParams defines parameters for ListNodeRecords.
type ListNodeRecordsParams struct {
	// Format The format specifies the format to filter the records by.
	Format *FormatFilter `form:"format,omitempty" json:"format,omitempty"`

	// CreatedAfter The createdAfter specifies the lowest creation time (exclusive) the resulting records can have.
	CreatedAfter *CreatedAfterFilter `form:"createdAfter,omitempty" json:"createdAfter,omitempty"`

	// CreatedBefore The createdBefore specifies the greatest creation time (exclusive) the resulting records can have.
	CreatedBefore *CreatedBeforeFilter `form:"createdBefore,omitempty" json:"createdBefore,omitempty"`

	// PageId The pageId specifies from which page to start return results.
	PageId *PageId `form:"pageId,omitempty" json:"pageId,omitempty"`

	// Limit The limit defines the max number of objects returned per page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateNodeRecordsMultipartBody defines parameters for CreateNodeRecords.
type CreateNodeRecordsMultipartBody struct {
	// File The document binary data in the specified format.
	File *openapi_types.File `json:"file,omitempty"`

	// Meta The object is used for records creation.
	Meta *CreateRecordsRequest `json:"meta,omitempty"`
}

// CreateFormatJSONRequestBody defines body for CreateFormat for application/json ContentType.
type CreateFormatJSONRequestBody = Format

// DeleteNodesJSONRequestBody defines body for DeleteNodes for application/json ContentType.
type DeleteNodesJSONRequestBody = DeleteNodesRequest

// UpdateNodeJSONRequestBody defines body for UpdateNode for application/json ContentType.
type UpdateNodeJSONRequestBody = Node

// PatchNodeRecordsJSONRequestBody defines body for PatchNodeRecords for application/json ContentType.
type PatchNodeRecordsJSONRequestBody = PatchRecordsRequest

// CreateNodeRecordsJSONRequestBody defines body for CreateNodeRecords for application/json ContentType.
type CreateNodeRecordsJSONRequestBody = CreateRecordsRequest

// CreateNodeRecordsMultipartRequestBody defines body for CreateNodeRecords for multipart/form-data ContentType.
type CreateNodeRecordsMultipartRequestBody CreateNodeRecordsMultipartBody

// SearchJSONRequestBody defines body for Search for application/json ContentType.
type SearchJSONRequestBody = SearchRecordsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List formats
	// (GET /formats)
	ListFormats(c *gin.Context)
	// Create new format
	// (POST /formats)
	CreateFormat(c *gin.Context)
	// Delete format
	// (DELETE /formats/{formatId})
	DeleteFormat(c *gin.Context, formatId FormatId)
	// Get format
	// (GET /formats/{formatId})
	GetFormat(c *gin.Context, formatId FormatId)
	// Delete multiple nodes
	// (DELETE /nodes)
	DeleteNodes(c *gin.Context)
	// List nodes
	// (GET /nodes)
	ListNodes(c *gin.Context, params ListNodesParams)
	// Delete node
	// (DELETE /nodes/{path})
	DeleteNode(c *gin.Context, path Path, params DeleteNodeParams)
	// Update node
	// (PUT /nodes/{path})
	UpdateNode(c *gin.Context, path Path)
	// List node records
	// (GET /nodes/{path}/records)
	ListNodeRecords(c *gin.Context, path Path, params ListNodeRecordsParams)
	// Patch node records
	// (PATCH /nodes/{path}/records)
	PatchNodeRecords(c *gin.Context, path Path)
	// Create node records
	// (POST /nodes/{path}/records)
	CreateNodeRecords(c *gin.Context, path Path)
	// Health check
	// (GET /ping)
	Ping(c *gin.Context)

	// (POST /search)
	Search(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListFormats operation middleware
func (siw *ServerInterfaceWrapper) ListFormats(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListFormats(c)
}

// CreateFormat operation middleware
func (siw *ServerInterfaceWrapper) CreateFormat(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateFormat(c)
}

// DeleteFormat operation middleware
func (siw *ServerInterfaceWrapper) DeleteFormat(c *gin.Context) {

	var err error

	// ------------- Path parameter "formatId" -------------
	var formatId FormatId

	err = runtime.BindStyledParameter("simple", false, "formatId", c.Param("formatId"), &formatId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter formatId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteFormat(c, formatId)
}

// GetFormat operation middleware
func (siw *ServerInterfaceWrapper) GetFormat(c *gin.Context) {

	var err error

	// ------------- Path parameter "formatId" -------------
	var formatId FormatId

	err = runtime.BindStyledParameter("simple", false, "formatId", c.Param("formatId"), &formatId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter formatId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFormat(c, formatId)
}

// DeleteNodes operation middleware
func (siw *ServerInterfaceWrapper) DeleteNodes(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteNodes(c)
}

// ListNodes operation middleware
func (siw *ServerInterfaceWrapper) ListNodes(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNodesParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", c.Request.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter path: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListNodes(c, params)
}

// DeleteNode operation middleware
func (siw *ServerInterfaceWrapper) DeleteNode(c *gin.Context) {

	var err error

	// ------------- Path parameter "path" -------------
	var path Path

	err = runtime.BindStyledParameter("simple", false, "path", c.Param("path"), &path)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter path: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteNodeParams

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", c.Request.URL.Query(), &params.Force)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter force: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteNode(c, path, params)
}

// UpdateNode operation middleware
func (siw *ServerInterfaceWrapper) UpdateNode(c *gin.Context) {

	var err error

	// ------------- Path parameter "path" -------------
	var path Path

	err = runtime.BindStyledParameter("simple", false, "path", c.Param("path"), &path)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter path: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateNode(c, path)
}

// ListNodeRecords operation middleware
func (siw *ServerInterfaceWrapper) ListNodeRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "path" -------------
	var path Path

	err = runtime.BindStyledParameter("simple", false, "path", c.Param("path"), &path)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter path: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNodeRecordsParams

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", c.Request.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter format: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "createdAfter" -------------

	err = runtime.BindQueryParameter("form", true, false, "createdAfter", c.Request.URL.Query(), &params.CreatedAfter)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter createdAfter: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "createdBefore" -------------

	err = runtime.BindQueryParameter("form", true, false, "createdBefore", c.Request.URL.Query(), &params.CreatedBefore)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter createdBefore: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageId" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageId", c.Request.URL.Query(), &params.PageId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListNodeRecords(c, path, params)
}

// PatchNodeRecords operation middleware
func (siw *ServerInterfaceWrapper) PatchNodeRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "path" -------------
	var path Path

	err = runtime.BindStyledParameter("simple", false, "path", c.Param("path"), &path)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter path: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchNodeRecords(c, path)
}

// CreateNodeRecords operation middleware
func (siw *ServerInterfaceWrapper) CreateNodeRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "path" -------------
	var path Path

	err = runtime.BindStyledParameter("simple", false, "path", c.Param("path"), &path)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter path: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateNodeRecords(c, path)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Ping(c)
}

// Search operation middleware
func (siw *ServerInterfaceWrapper) Search(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Search(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/formats", wrapper.ListFormats)
	router.POST(options.BaseURL+"/formats", wrapper.CreateFormat)
	router.DELETE(options.BaseURL+"/formats/:formatId", wrapper.DeleteFormat)
	router.GET(options.BaseURL+"/formats/:formatId", wrapper.GetFormat)
	router.DELETE(options.BaseURL+"/nodes", wrapper.DeleteNodes)
	router.GET(options.BaseURL+"/nodes", wrapper.ListNodes)
	router.DELETE(options.BaseURL+"/nodes/:path", wrapper.DeleteNode)
	router.PUT(options.BaseURL+"/nodes/:path", wrapper.UpdateNode)
	router.GET(options.BaseURL+"/nodes/:path/records", wrapper.ListNodeRecords)
	router.PATCH(options.BaseURL+"/nodes/:path/records", wrapper.PatchNodeRecords)
	router.POST(options.BaseURL+"/nodes/:path/records", wrapper.CreateNodeRecords)
	router.GET(options.BaseURL+"/ping", wrapper.Ping)
	router.POST(options.BaseURL+"/search", wrapper.Search)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W/kthH/Vwi1RWxAsX25vNRAHi4JLjWatm5yfYoNmCuOdpmTSIUc2V4c9n8vhqS+",
	"Ka1sn9M89OnOK37M/OZ7hp+STJeVVqDQJpefkoobXgKCcX99Z4AjiHc5gnkvCwRDvwqwmZEVSq2Sy+TD",
	"DljWW8dsBZnMJViGO2CFfgCLfoXUiqEsgZ3AY1bUVt7DqVtkwNYFSrVlBjJthGUZV2zH7+EsSRNJ1/xW",
	"g9knaaJ4Ccll0r8xSROb7aDkRFyuTckxuUwER/iSbkvSBPcVbbJopNomh0PacPYt5NrACtb8whFvW/ft",
	"9bjzlz6HvffaZDBlKKefWV7wbY+Thx3gDowjVVdgPCcPsiiYX+95+K0Gi3MEu4UDQgNNG60L4KohquS4",
	"BLbnboRy+BE1y93WQI9HcrNfIImQitA0xKnkeCUWyZECFBI9pr2r4rgbX3UlkjQhnKQBkVyiqWH58h9l",
	"KTF+c0GfmIBcqoBCyR+ZqssNGKZzpje/QoaWGcDaKBCsAsMqvp3VKHdgDAypELZgHEHXfAtzWFTuW080",
	"udEle9jJbOe+kXwscoOBpqD1do4gf94R8VwTzFFylBZEE+7YSSeeU/YgcSeVA0wqAY8zAgt/PUVYRMqS",
	"6jpahorrfurUdl5VAzlL13/gW7t0PfKtHV3vfnqq1dCmASl/NpAnl8mfzrs4ce6/2nMiKjkQeeGXLmb8",
	"5G/6ybuNOM1eiZm0rLYgyNo6BxkcKpFZGfJKKMEdL3RWl6BmjtxIxc2eCY7cnUdMNzvIbujvBiUR7Jvu",
	"aN3qZo8Rj5ompG8f3I/LkPyzWXdIKZbaeXWhb4xQZyfBz9AfpySxDXSIDDjYaOEkNyHPcPXxHxRkqkI2",
	"V+a8LjC5fJPGrjdSG4l7lmnIc5lJOv2krC3S5Tf1xcVb+Ia9Obs4bVBrJBMsjDML3GS7YObMAqZu3T0v",
	"aiCZ6nswRgoBim32/ogBkWHlQBqMK7JbeS9FzYtwZ49h7wAdw56cOe9pnbQbmnHHkTXMcSFAEMoY3Igz",
	"BYTSHpOt12m6PZDDjeF79zcZwjpj6XudXzq1ShvLC0qTdoreMTuR821LirelpM1sWvuzTglWmB+3jJM0",
	"K60sjKXeJji9PGBol8SJDVnVslTcyiavWg0+GVYM+kDh4s1d3BzwA33V6sfBsYTa0yfXxQTwPRSAQPQ+",
	"yf2hZsLtZKUXMASkODLOQqY3xNx79u+0EpLOnbGG4P+zdtkZ6362zNZVpQ2yO67EXcrutLljXAl2pzTe",
	"9XY5+7zzrorWUdAKK5FvT25cBLlJTu9St1Iqi1xlkDafq3pTyOwmOWXfsJuEAu5N4rYH70e/2soAF3YH",
	"gPZ7jjysOHGRlBaca7O152++evv1+YYXdP7ZY2EfbxKmjY+3hfwIYeFfbpLT07uov8zj+bHDhbJjXhT6",
	"wfZkku1kIQwoUiLOSo7ZDoQTUMrgHhSTzmD2TGj1BbISAH3yGsA3EsFI3tHST4z7+jaRaUNsTNXeh7C1",
	"oF7+w4b0qA2LIegNlWnDrbSLebBb0c8A/c9ClqCsU6xVkdQlGgvX0IKUyYFnwrlsfJopDYyXO6vxrM0D",
	"aJ/vID1R1ju3WeeYz13znVbIpaKTG/cY1q52jEEHJq5xrFeBhBgKP0qLwV+9LFx4h7WMRcvUkQjxwsgw",
	"Yt+fNMf8M6Jlx3tIJQLXPr7Mh0l4xKUyS4oWS3hEX1mRO90Cug5C6CfgKEDHk8I1OVKuayX6x7w0FdLI",
	"i5kahT71gvHk6iOh2FPWXBGTpVOFdd6wLRHbHHAkqFk35UpP76SanLJW8rcaGC91EJGVm0KqrWWhGEUD",
	"EJVRdbzCTZnQYJnSyKTKilr4jowrHSpuMHru+oy02by2rom72FDCYi+XnRNQU0Y9WUiMjiNuQdWl92mF",
	"GObKtxEorilYP6MeRc3qyoJBl4OEPKDxcn21HRWobuFPS7bX1iWu1PMbumrvM9UknvYn0OE3fG5CRuoy",
	"pCodoRVTmaH4nhmfgo+u6KzjTjpI5Fgx0QhuwYM1Yjh+WIv+en/YHp22FMcADJJZAi1r0hCpfJ5ApR7f",
	"6Bp7JthV47HkZjGlGwSrqL+SYklFe0lfv8XXKOj/rB2y0A2Jdi0sbOd7V/4IvimAIcX+xgwXULuHDPVM",
	"h8l/G7bCwv0r8vRx6HWd2kB9e2/aNdlXNCZ+dvw9zxFXYOiqBmaeGW3tRDcj3vj/JfKwRDaQy8cTn1b4",
	"tfNF8tbouvp2f81x9688X6iWsTbKMp3nTdOfua2Ur272Loc5ixS+aRhKRM8t+aMs6zLSuulPOqbuVue5",
	"BVzbBkLN7EdZsU2Y7vXmF35c144wpjeRjf7bNc/jyS6ZsGuue11y/20TRhIoCMoOeUakkJicM3E67dcW",
	"XG1ryv+Dy6mVAFPsibBgBqC2UsHxMrgjNY31F0ZybkFsBLTCmF8WllvneSQuL5SOvpaYOINVqUuElyuE",
	"8g9X3czRuRZ3xeiOpiSZgO5lMkU9NLv+DvuH+VSy6Yh9DKv6YboLYK04pvXKCOj5usg5uuMJhWmznnVZ",
	"q820gbkcpIB7rrI9c4uml7exNC+0i4ajwD+SdDt9dHenE4AbYmI68CHUdVx4++XF9UBYExxWVlm+vuLb",
	"vqY2txL9lBhO0flZlrKg5MfcywzYu+urG0X7JRbQfX53feVyBmP9rjdnF2cXzllXoHglk8vk7dnF2dtQ",
	"Rjo+znsts23Mof8oLfZ7Ze3LhSsRvja9PULa67Y77auLN/QPpbwhFeNVVcjMbT7/1dLpn1YOQJsrHESz",
	"2W/oDKGRcA+C2TrLwNq8Lor9mVMOW5clp0Ay4Kqpoy9/aduUt2QZOpY2+YEE40zBQ9spzZlE1zxQXyCD",
	"Rzp77zPTIVp+8/s2l/P+91st9p8ZKQ/UcOx+eHX5HBHPA2/nQWPZpMnXF39drGzamO3aMbyg5GzvsbZj",
	"4QYZdRKKSviQtsp//ql5WXLoytIpOX7g1DT2WY+6jKt+h8ErhPS9JB8WlHB/2L2l0OAfnIiphvgrWg3p",
	"vxL7JS6Cbsl5+8jmcDuR9dfL6HLbEh8RzdvFzZmuC89dDwIrKdPyKIyZdmceJ4hOdMF9lYJ4VWCb2klj",
	"RI2owc+YKlACVCZhojQD4c64hKiD/AGwN+sZivMHwFeQ5cXvb7ezXvW4KOVQkgPQO+xmTdTNKJas0j0e",
	"5EUxnSWO5rv+DdVkYtjP0GPG6AY2r+StIyPsVZ47gvjPumwZBdOqvpfQxUzu2r5C7EwmdABoZ8w+hpj2",
	"pOZhmrUSF3DbedM0iWhQfpqV9B6LvaqdjAd3MwYzGMutTkPmkGy1//wTpWtrQpPLLk8o2JBBNLP007MF",
	"1X4W5skhXePBMnhCKHK0HwlEx7bOOpoePlGdreqIzv6nEhy77ucQQf/xBQjevo5L8VPaNU7k4giYtePw",
	"88qhB+kKjT/vTVaXvUq//o87l24U8mrq3j26XrE+8uR//a7Bc/oV28IkfMVK/1b61Z3psKE1407Hzwuf",
	"k4QcV8mJDvUUs52X+U5JFmmVuLHZER10a16uhK/kMWJz2/UO5BVIWNKJ9nks5ThVaIZ9TnWYynNOH5b6",
	"AwN9YF2KmmVQoWX4oJmQeQ4GlJ8K0r+4r8CyLxlh5ypGl2y5eYzgyOf6CX9YxYq+UCe0fRLJDboC/Eti",
	"bnjqZLY0k/d3D7Z779Gbvuvi83O3PtbPLAGfz1ikoff7NWFiD5LXWNHTezKD7WRJzRGhzuak0nkhM5xr",
	"zRwzL8oEKpLIXOT/G/ACdyzbQfYx9f+Ep6Hs3fWV65SCcV35ypmSqZWSahvxzXTLC13beCoUxdyN6cj1",
	"dDiP0ekz1YPFkegx8cMEZyJR9+NHF34otjS8HWLgd71SjRsdR//O8SU2RZsRUxjXxATVyCPAdXs4HA7/",
	"DQAA///drv952DkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
